version: "3"

networks:
  web_network:
    driver: bridge

services:

#  redis:
#    restart: always
#    image: redis:latest
#    command:  redis-server
#    expose:
#    - "6379"
#    networks:
#    - web_network

  app:
    restart: always
    # where the app Dockerfile locates, the . means current dir
    build: .
    command: gunicorn -c gunicorn.py manage:app
    volumes:
      - .:/code
    expose:
      - "8000"
    networks:
      - web_network
#    depends_on:
#      - redis

  nginx:
    restart: always
    image: nginx:latest
    ports:
    - "8080:8000"  # 宿主机 8080 端口映射到容器 8000 端口 (HTTP)
    - "8443:443"   # 宿主机 8443 端口映射到容器 443 端口 (HTTPS)
    volumes:
    - ./config/nginx:/etc/nginx/conf.d
    - ./config/https-cert:/etc/nginx/certs
    depends_on:
    - app
#    - redis
    networks:
    - web_network
    tty: true
    stdin_open: true










