"""Use core models instead of Flask-SQLAlchemy models

Revision ID: 9ecae462416c
Revises: a38d8070ec45
Create Date: 2025-12-21 12:47:13.503365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ecae462416c'
down_revision = 'a38d8070ec45'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generation_time', sa.Float(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('generation_time')
    # ### end Alembic commands ###
